### ISSUE TITLE
Implement Dereferencing for the secondary resource

### ISSUE THREAD

**Issue by anikitinDSR** [cheqd/did-resolver#6]
Dereferencing for the primary resource is already implemented. For this issue we want to have Implemented dereferencing for the secondary resource as described in doc:
https://w3c-ccg.github.io/did-resolution/#dereferencing-algorithm-secondary

# Links for context
https://w3c-ccg.github.io/did-resolution/

**Comment by Toktar** [comment]
I suggest to start with `service` and `relativeRef`.
Hey @Tweeddalex,  re-read the spec. Formed a clearer opinion.
As I see myself dereferencing these resources: 
DID Doc:
```
{
	"@context": "https://www.w3.org/ns/did/v1",
	"id": "did:example:123456789abcdefghi",
	"verificationMethod": [{
		"id": "did:example:123456789abcdefghi#message_key",
		"type": "Ed25519VerificationKey2018",
		"controller": "did:example:123456789abcdefghi",
		"publicKeyBase58": "H3C2AVvLMv6gmMNam3uVAjZpfkcJCwDwnZn6z3wXmqPV"
	}],
	"service": [{
		"id": "did:example:123456789abcdefghi#message",
		"type": "MessagingService",
		"serviceEndpoint": "https://example1.com"
	}, {
		"id": "did:example:123456789abcdefghi#my_message",
		"type": "MessagingService",
		"serviceEndpoint": "https://example2.com"
	}]
}
```
`service` - get SeviceEndpoint by id. The value of this query should be exactly the same with a fragment id.

**Example 1 - get clean endpoint**
Input DID URL: `did:example:123456789abcdefghi?service=message`
Output contentStream: `{ "https://example1.com" }`

**Example 2 - not found**
Input DID URL: `did:example:123456789abcdefghi?service=mess`
Output contentStream: `{}`, error - notFound

**Example 3 - hash simbol**
Input DID URL: `did:example:123456789abcdefghi?service=message#flag`
Output contentStream: `{ "https://example1.com#flag" }`
Note: don't process `flag` like a DID fragment id, just add to ServiceEndpoint

**Example 4 - relativeRef**
Input DID URL: `did:example:123456789abcdefghi?service=message&relativeRef=%2Fsome%2Fpath%3Fsome_query`
Output contentStream: `{ "https://example1.com/some/path?some_query" }`
Note: 
`relativeRef` is a parameter name, 
`%2Fsome%2Fpath%3Fsome_query` is a value. After URL decoding, the value is `/some/path?some_query`
It means that for getting this output we need
1. Resolve DID `did:example:123456789abcdefghi` - get DID doc
2. Get Service Endpoint by id `message`.  Result  - ServiceEndpoint URL https://example1.com. Like in Example 1
3. Add the encoded value of `relativeRef` to the URL from the previous step. `https://example1.com` + `/some/path?some_query`

**Example 5 - relativeRef + hash simbol**
Input DID URL: `did:example:123456789abcdefghi?service=message&relativeRef=%2Fsome%2Fpath%3Fsome_query#flag`
Output contentStream: `{ "https://example1.com/some/path?some_query#flag" }`
Note: the same steps with Example 4 + 
4. just add  `#flag` to ServiceEndpoint.

**Example 6 - primary resource without service**
Input DID URL: `did:example:123456789abcdefghi?#messege`
Output contentStream: 
```
{
		"id": "did:example:123456789abcdefghi#message",
		"type": "MessagingService",
		"serviceEndpoint": "https://example1.com"
}
```
Note: here we process a value after `#` because after processing the previous part we have a full DID Doc (primary resource), not just SeviceEndpoint string like in the previous examples

**Example 7 - representationNotSupported**
Input DID URL: `did:example:123456789abcdefghi?relativeRef=%2Fsome%2Fpath%3Fsome_query`
Output contentStream: `{ }`;  error - representationNotSupported

@Tweeddalex @ankurdotb Could you please approve this approach. If you agree, @IlAganin will start to implement this.

СС: @anikitinDSR

**Comment by Tweeddalex** [comment]
@filipdjokic after the release lets align on how you can pick this up
